insert into address (street, city, country, customer_id) values ('street12', 'Giza', 'Egypt', 1022);
insert into address (street, city, country, customer_id) values ('street 4', 'Cairo', 'Egypt', 1033);
insert into address (street, city, country, customer_id) values ('street 4', 'Cairo', 'Egypt', 1044);
insert into address (street, city, country, customer_id) values ('street 2', 'Cairo', 'Egypt', 1055);
insert into address (street, city, country, customer_id) values ('street 2', 'Banha', null, 1066);
insert into address (street, city, country, customer_id) values ('street 14', 'Cairo', 'Egypt', 1077);
insert into address (street, city, country, customer_id) values ('street 10', 'Giza', 'Egypt', 1088);
insert into address (street, city, country, customer_id) values ('street 5', 'Cairo', 'Egypt', 1099);
insert into address (street, city, country, customer_id) values ('street 2', 'Banha', 'Egypt', 1110);
insert into address (street, city, country, customer_id) values ('street 4', 'Cairo', 'Egypt', 1121);
insert into address (street, city, country, customer_id) values ('street 2', 'Cairo', 'Egypt', 1132);
insert into address (street, city, country, customer_id) values ('street 4', 'Banha', 'Egypt', 1143);
insert into address (street, city, country, customer_id) values ('street 10', 'Banha', 'Egypt', 1154);
insert into address (street, city, country, customer_id) values ('street 14', 'Giza', 'Egypt', 1165);
insert into address (street, city, country, customer_id) values ('street 2', 'Cairo', 'Egypt', 1176);
insert into address (street, city, country, customer_id) values ('street 8', 'Cairo', 'Egypt', 1187);
insert into address (street, city, country, customer_id) values ('street 5', 'Giza', 'Egypt', 1198);
insert into address (street, city, country, customer_id) values ('street 14', 'Cairo', null, 1209);
insert into address (street, city, country, customer_id) values ('street 8', 'Cairo', 'Egypt', 1220);
insert into address (street, city, country, customer_id) values ('street 10', 'Giza', null, 1231);
insert into address (street, city, country, customer_id) values ('street 5', 'Banha', 'Egypt', 1242);
insert into address (street, city, country, customer_id) values ('street 2', 'Alex', 'Egypt', 1253);
insert into address (street, city, country, customer_id) values ('street 10', 'Cairo', null, 1264);
insert into address (street, city, country, customer_id) values ('street 5', 'Giza', null, 1275);
insert into address (street, city, country, customer_id) values ('street 4', 'Alex', 'Egypt', 1286);
insert into address (street, city, country, customer_id) values ('street 2', 'Banha', null, 1297);
insert into address (street, city, country, customer_id) values ('street 5', 'Banha', 'Egypt', 1308);
insert into address (street, city, country, customer_id) values ('street 14', 'Cairo', 'Egypt', 1319);
insert into address (street, city, country, customer_id) values ('street 2', 'Banha', 'Egypt', 1330);
insert into address (street, city, country, customer_id) values ('street 5', 'Alex', 'Egypt', 1341);
insert into address (street, city, country, customer_id) values ('street 8', 'Giza', 'Egypt', 1352);
insert into address (street, city, country, customer_id) values ('street 4', 'Cairo', null, 1363);
insert into address (street, city, country, customer_id) values ('street 10', 'Giza', null, 1374);
insert into address (street, city, country, customer_id) values ('street 4', 'Cairo', null, 1385);
insert into address (street, city, country, customer_id) values ('street 8', 'Cairo', 'Egypt', 1396);
insert into address (street, city, country, customer_id) values ('street 10', 'Alex', 'Egypt', 1407);
insert into address (street, city, country, customer_id) values ('street 4', 'Giza', null, 1418);
insert into address (street, city, country, customer_id) values ('street12', 'Cairo', null, 1429);
insert into address (street, city, country, customer_id) values ('street 14', 'Giza', 'Egypt', 1440);
insert into address (street, city, country, customer_id) values ('street 2', 'Giza', 'Egypt', 1451);
insert into address (street, city, country, customer_id) values ('street12', 'Alex', 'Egypt', 1462);
insert into address (street, city, country, customer_id) values ('street 5', 'Alex', 'Egypt', 1473);
insert into address (street, city, country, customer_id) values ('street 14', 'Cairo', 'Egypt', 1484);
insert into address (street, city, country, customer_id) values ('street 4', 'Alex', 'Egypt', 1495);
insert into address (street, city, country, customer_id) values ('street 10', 'Cairo', 'Egypt', 1506);
insert into address (street, city, country, customer_id) values ('street 8', 'Banha', null, 1517);
insert into address (street, city, country, customer_id) values ('street 10', 'Giza', 'Egypt', 1528);
insert into address (street, city, country, customer_id) values ('street 5', 'Cairo', null, 1539);
insert into address (street, city, country, customer_id) values ('street 2', 'Banha', 'Egypt', 1550);
insert into address (street, city, country, customer_id) values ('street 8', 'Giza', 'Egypt', 1561);
insert into address (street, city, country, customer_id) values ('street 10', 'Giza', 'Egypt', 1572);
insert into address (street, city, country, customer_id) values ('street 8', 'Cairo', 'Egypt', 1583);
insert into address (street, city, country, customer_id) values ('street 5', 'Cairo', 'Egypt', 1594);
insert into address (street, city, country, customer_id) values ('street 2', 'Giza', 'Egypt', 1605);
insert into address (street, city, country, customer_id) values ('street 5', 'Giza', 'Egypt', 1616);
insert into address (street, city, country, customer_id) values ('street 14', 'Alex', 'Egypt', 1627);
insert into address (street, city, country, customer_id) values ('street 4', 'Alex', 'Egypt', 1638);
insert into address (street, city, country, customer_id) values ('street12', 'Giza', 'Egypt', 1649);
insert into address (street, city, country, customer_id) values ('street 10', 'Giza', null, 1660);
insert into address (street, city, country, customer_id) values ('street 14', 'Alex', 'Egypt', 1671);
insert into address (street, city, country, customer_id) values ('street 8', 'Cairo', 'Egypt', 1682);
insert into address (street, city, country, customer_id) values ('street 10', 'Giza', null, 1693);
insert into address (street, city, country, customer_id) values ('street 5', 'Cairo', 'Egypt', 1704);
insert into address (street, city, country, customer_id) values ('street 4', 'Banha', 'Egypt', 1715);
insert into address (street, city, country, customer_id) values ('street 5', 'Banha', 'Egypt', 1726);
insert into address (street, city, country, customer_id) values ('street12', 'Banha', 'Egypt', 1737);
insert into address (street, city, country, customer_id) values ('street12', 'Banha', 'Egypt', 1748);
insert into address (street, city, country, customer_id) values ('street 8', 'Alex', 'Egypt', 1759);
insert into address (street, city, country, customer_id) values ('street12', 'Giza', 'Egypt', 1770);
insert into address (street, city, country, customer_id) values ('street 5', 'Cairo', 'Egypt', 1781);
insert into address (street, city, country, customer_id) values ('street 14', 'Giza', 'Egypt', 1792);
insert into address (street, city, country, customer_id) values ('street 14', 'Alex', 'Egypt', 1803);
insert into address (street, city, country, customer_id) values ('street 8', 'Cairo', 'Egypt', 1814);
insert into address (street, city, country, customer_id) values ('street12', 'Banha', 'Egypt', 1825);
insert into address (street, city, country, customer_id) values ('street 2', 'Cairo', 'Egypt', 1836);
insert into address (street, city, country, customer_id) values ('street 10', 'Cairo', 'Egypt', 1847);
insert into address (street, city, country, customer_id) values ('street 5', 'Alex', 'Egypt', 1858);
insert into address (street, city, country, customer_id) values ('street12', 'Cairo', 'Egypt', 1869);
insert into address (street, city, country, customer_id) values ('street 14', 'Banha', 'Egypt', 1880);
insert into address (street, city, country, customer_id) values ('street12', 'Giza', 'Egypt', 1891);
insert into address (street, city, country, customer_id) values ('street 2', 'Alex', 'Egypt', 1902);
insert into address (street, city, country, customer_id) values ('street12', 'Alex', 'Egypt', 1913);
insert into address (street, city, country, customer_id) values ('street 14', 'Giza', 'Egypt', 1924);
insert into address (street, city, country, customer_id) values ('street 5', 'Alex', 'Egypt', 1935);
insert into address (street, city, country, customer_id) values ('street12', 'Cairo', 'Egypt', 1946);
insert into address (street, city, country, customer_id) values ('street 8', 'Giza', 'Egypt', 1957);
insert into address (street, city, country, customer_id) values ('street12', 'Cairo', 'Egypt', 1968);
insert into address (street, city, country, customer_id) values ('street 10', 'Giza', 'Egypt', 1979);
insert into address (street, city, country, customer_id) values ('street 5', 'Alex', 'Egypt', 1990);
insert into address (street, city, country, customer_id) values ('street 8', 'Banha', 'Egypt', 2001);
insert into address (street, city, country, customer_id) values ('street12', 'Cairo', 'Egypt', 2012);
insert into address (street, city, country, customer_id) values ('street 8', 'Alex', 'Egypt', 2023);
insert into address (street, city, country, customer_id) values ('street 4', 'Cairo', 'Egypt', 2034);
insert into address (street, city, country, customer_id) values ('street12', 'Banha', 'Egypt', 2045);
insert into address (street, city, country, customer_id) values ('street 4', 'Alex', 'Egypt', 2056);
insert into address (street, city, country, customer_id) values ('street 2', 'Cairo', 'Egypt', 2067);
insert into address (street, city, country, customer_id) values ('street 14', 'Cairo', 'Egypt', 2078);
insert into address (street, city, country, customer_id) values ('street 4', 'Giza', 'Egypt', 2089);
insert into address (street, city, country, customer_id) values ('street 14', 'Giza', null, 2100);
insert into address (street, city, country, customer_id) values ('street12', 'Banha', 'Egypt', 2111);
